# Python Basics

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

1. What is 5 to the power of 5?

In [2]:
5 ** 5

3125

2. What is the remainder from dividing 73 by 6?

In [3]:
73 % 6

1

3. How many times does the whole number 3 go into 123? What is the remainder of dividing 123 by 3?


In [4]:
123 // 3
123 % 3

41

0

4. Split the following string into a list by splitting on the space character:<br><br>
 `s = "MDS is going virtual!"`

In [5]:
s = "MDS is going virtual!"
list_s = s.split(' ')
list_s

['MDS', 'is', 'going', 'virtual!']

5. Given the following variables:<br><br>
`thing = "light"`<br>
`speed = 299792458  # m/s`<br><br>
`use f-strings to print`<br>
`The speed of light is 2.997925e+08 m/s.`

In [6]:
print(f'The speed of light is {"{:e}".format(299792458)} m/s')

The speed of light is 2.997925e+08 m/s


6. Given this nested list, use indexing to grab the word “MDS”:<br><br>
`l = [10, [3, 4], [5, [100, 200, ["MDS"]], 23, 11], 1, 7]`


In [7]:
l = [10, [3, 4], [5, [100, 200, ["MDS"]], 23, 11], 1, 7]
l[2][1][2][0]

'MDS'

7. Given this nest dictionary grab the word “MDS”:<br><br>

In [8]:
d = {
    "outer": [
        1,
        2,
        3,
        {"inner": ["this", "is", "inception", {"inner_inner": [1, 2, 3, "MDS"]}]},
    ]
}
d['outer'][3]['inner'][3]['inner_inner'][3]

'MDS'

8. Why does the following cell return an error?<br><br>
`t = (1, 2, 3, 4, 5)`<br>
`t[-1] = 6`

In [9]:
print('Tuples are Immutable.')

Tuples are Immutable.


9. Use string methods to extract the website domain from an email, e.g., from the string "tomas.beuzen@fakemail.com", you should extract "fakemail".


In [10]:
email = "tomas.beuzen@fakemail.com"
email.split('@')[1].split('.')[0]

'fakemail'

10. Given the variable language which contains a string, use if/elif/else to write a program that:
- return “I love snakes!” if language is "python" (any kind of capitalization)
- return “Are you a pirate?” if language is "R" (any kind of capitalization)
- else return “What is language?” if language is anything else.

In [11]:
language = input('Enter language: ')
if language.lower() == 'python':
    print('I love snakes!')
elif language.lower() == 'r':
    print('Are you a pirate? ')
else:
    print('What is language?')

I love snakes!


# Loops & Functions

1. Create a function website() that grabs the website domain from a url string. For example, if your function is passed "www.google.com", it should return "google".

In [12]:
def website(url):
    return url.split('.')[1]

website('www.google.com')
website('www.abc.com')

'google'

'abc'

2. Create a function divisible(a, b) that accepts two integers (a and b) and returns True if a is divisble by b without a remainder. For example, divisible(10, 3) should return False, while divisible(6, 3) should return True.

In [13]:
def divisible(a, b):
    if a % b == 0:
        return True
    return False

divisible(10, 3)
divisible(6, 3)

False

True

3. Use list comprehension to square every number in the following list of numbers.<br><br>
`l = [1, 2, 3, 4, 5, 6, 7, 8, 9]`

In [14]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]

l_sq = [number** 2 for number in l]
l_sq

[1, 4, 9, 16, 25, 36, 49, 64, 81]

4. For the following list of names, write a list comprehension that creates a list of only words that start with a capital letter (hint: str.isupper()).<br><br>

`names = ['Steve Irwin', 'koala', 'kangaroo', 'Australia', 'Sydney', 'desert']`

In [15]:
names = ['Steve Irwin', 'koala', 'kangaroo', 'Australia', 'Sydney', 'desert']
upper_case_names = [name for name in names if name[0].isupper()]
upper_case_names

['Steve Irwin', 'Australia', 'Sydney']

5. For the following list of keys and vals use dictionary comprehension to create a dictionary of the form {'key-0': 0, 'key-1': 1, etc} (hint: zip() can help you combine two lists into on object to be used for comprehension/looping).<br><br>
`keys = [f"key-{k}" for k in range(10)]`<br>
`vals = range(10)`<br>

In [16]:
keys = [f"key-{k}" for k in range(10)]
vals = range(10)


6. This question is a little harder. Create a generator function called listgen(n) that yields numbers from 0 to n, in batches of lists of maximum 10 numbers at a time. For example, your function should behave as follows:<br><br>
`g = listgen(100)`<br>
`next(g)`<br>
`[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`<br>
`next(g)`<br>
`[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]`<br>
`next(g)`<br>
`[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]`<br>
`etc.`<br>
`g = listgen(5)`<br>
`next(g)`<br>

In [17]:
def listgen(n):
    for i in range(n):
        yield i

g = listgen(100)
next(g)

0

7. Write a try/except to catch the error generated from the following code and print “I caught you!”. Make sure you catch the specific error being caused, this is typically better practice than just catching all errors!

In [18]:
try:
    5/0
except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
except ValueError:
    print("Error: The file does not contain a valid integer.")
except ZeroDivisionError:
    print("Error: Division by zero.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")


Error: Division by zero.


8. Create a function lucky_sum() that takes all the integers a user enters and returns their sum. However, if one of the values is 13 then it does not count towards the sum, nor do any values to its right.

For example, your function should behave as follows: <br><br>

`lucky_sum(1, 2, 3, 4)`<br>
`10`<br>
`lucky_sum(1, 13, 3, 4)`<br>
`1`<br>
`lucky_sum(13)`<br>
`0`


In [19]:
def lucky_sum(*args):
    if 13 in args:
        return sum(args[:args.index(13)])
    return sum(args)

lucky_sum(1,2,3,4)
lucky_sum(1,13,3,4)
lucky_sum(13)

10

1

0

# Unit Tests & Classes

In [20]:
import math

1. The function area() accepts the argument radius and calculates the area of a circle. Write three tests using assert statements for the following conditions:

- Assert that area(1) returns a float;
- Assert that area(0) returns a value of 0;
- Assert that area(5) is approximately equal to 78.5 (hint: math.isclose(..., abs_tol=0.1))

In [21]:
def area(radius):
    """Calculate the area of a circle based on the given radius."""
    return math.pi * radius ** 2

In [22]:
assert isinstance(area(1),float), 'float error'
assert area(0) == 0, 'value must be 0'
assert math.isclose(area(5),78.5, abs_tol=0.1), 'must be clost to 78.5'

2. In the spirit of the EAFP (easier to ask for forgiveness than permission) philosophy. Modify the code of the function area() and add a try/except statement to catch the type error raised by passing a string to area() as shown below:


In [23]:
def area(radius):
    """Calculate the area of a circle based on the given radius."""
    try:
        return math.pi * radius ** 2
    except TypeError:
        print("Error: Radius must be a number.")
    except Exception as e:
        print(f"An error occurred: {e}")

area('10')

Error: Radius must be a number.


3. In the spirit of the LBYL (look before you leap) philosophy. Modify the code of the function area() and add a conditional if/else statement to make sure that a user has passed a number (int or float) to the area() function. If they pass something else, raise a TypeError.

In [24]:
def area(radius):
    """Calculate the area of a circle based on the given radius."""
    
    if isinstance(radius, (int, float)):
        return math.pi * radius ** 2
    
    raise TypeError("The radius must be a number.")

area(1)

3.141592653589793

4. For this exercise I want you to create a class called Circle. It should have the following characteristics:

It should be initiated with the argument radius and store this as an instance attribute.

Have a method area() which calculates the area of the circle.

Have a method circumference() which calculates the circumference of the circle.

Have the method __str__() which is a special method in Python and controls what is output to the screen when you print() an instance of your class (learn more here). The print() statement should print the string f"A Circle with radius {self.radius}".

I’ve provided some tests for you to check your class.

In [25]:
class Circle:
    """A circle with a radius r."""
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        """Returns the area of the circle."""
        return 3.14 * self.radius ** 2

    def circumference(self):
        """Returns the circumefrence of the circle."""
        return 2 * 3.14 * self.radius

    def __str__(self):
        return f"A Circle with radius {self.radius}"
    
obj = Circle(5)
obj.area()
obj.circumference()
obj.__str__()

78.5

31.400000000000002

'A Circle with radius 5'

In [26]:
assert Circle(3).radius == 3, "Test 1 failed."
assert math.isclose(Circle(3).area(), 28.3, abs_tol=0.1), "Test 2 failed."
assert math.isclose(Circle(3).circumference(), 18.8, abs_tol=0.1), "Test 3 failed."
assert Circle(3).__str__() == "A Circle with radius 3", "Test 4 failed."

5. Now, let’s create a new class sphere that inherits from the circle class we created above. It should have the following characteristics:

It should be initiated exactly the same as Circle was, with the single argument radius which is stored as an instance attribute.

Have a method volume() which calculates the volume of the sphere (43𝜋𝑟3
).

Outputs the string f"A Sphere with volume 4.19" when you call print(Sphere(1)) (hint: recall the __str__() method from the previous question).

I’ve provided some tests for you to check your class.


In [27]:
class Sphere(Circle):
    def __init__(self, radius):
        self.radius = radius
    
    def volume(self):
        return (4 / 3) * math.pi * self.radius ** 3
    
    def __str__(self):
        return f'A Sphere with volume {self.volume():.2f}'

In [28]:
assert Sphere(3).radius == 3, "Test 1 failed."
assert math.isclose(Sphere(3).area(), 28.3, abs_tol=0.1), "Test 2 failed."
assert math.isclose(Sphere(3).circumference(), 18.8, abs_tol=0.1), "Test 3 failed."
assert math.isclose(Sphere(3).volume(), 113.1, abs_tol=0.1), "Test 3 failed."
assert Sphere(1).__str__() == "A Sphere with volume 4.19", "Test 4 failed."

6. Now, let’s create a new class sphere that inherits from the circle class we created above. It should have the following characteristics:

It should be initiated exactly the same as Circle was, with the single argument radius which is stored as an instance attribute.

Have a method volume() which calculates the volume of the sphere (43𝜋𝑟3
).

Outputs the string f"A Sphere with volume 4.19" when you call print(Sphere(1)) (hint: recall the __str__() method from the previous question).

I’ve provided some tests for you to check your class.


In [29]:
class Sphere(Circle):
    def __init__(self, radius):
        self.radius = radius
    
    def volume(self):
        return (4 / 3) * math.pi * self.radius ** 3
    
    def __str__(self):
        return f'A Sphere with volume {self.volume():.2f}'
    
    @classmethod
    def from_circ(cls, circumfrence):
        radius = circumfrence / (2 * math.pi)
        return cls(radius)

In [30]:
assert Sphere.from_circ(0).radius == 0, "Test 1 failed."
assert Sphere.from_circ(3 * math.pi).radius == 1.5, "Test 2 failed." 
assert math.isclose(Sphere.from_circ(6).radius, 0.95, abs_tol=0.1), "Test 3 failed."
assert math.isclose(Sphere.from_circ(6).volume(), 3.65, abs_tol=0.1), "Test 4 failed."
assert Sphere.from_circ(6).__str__() == "A Sphere with volume 3.65", "Test 5 failed."

# NUMPY

1. Import numpy under the alias np.

In [31]:
import numpy as np

2. Create the following arrays:

- Create an array of 5 zeros.
- Create an array of 10 ones.
- Create an array of 5 3.141s.
- Create an array of the integers 1 to 20.
- Create a 5 x 5 matrix of ones with a dtype int.

In [44]:
zero_array = np.zeros((5,))
one_array = np.ones((10,))
pi_array = np.repeat(3.141, 5)
first_20_nums_array = np.arange(1,21)
one_matrix = np.ones((5,5),dtype=int)

3. Use numpy to:

- Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: np.random.randn())
- Reshape the above array into shape (27,)

In [48]:
np.random.randn(3,3,3).reshape(27,)

array([ 1.85002291,  1.41395193,  0.57573614,  0.15133506,  0.04202688,
        0.68507616,  0.20138123,  1.04948221, -3.52739538, -2.02467227,
       -0.50225399, -0.70008306,  0.6360949 , -1.96663053,  0.84432891,
        0.97376557,  0.71880494,  0.25972306, -0.04173132,  0.69342175,
        1.31678744,  0.22489574, -2.55705985,  1.00221273,  0.07722073,
        0.08565814,  1.16787152])

4. Create an array of 20 linearly spaced numbers between 1 and 10.

In [50]:
linspaced_20 = np.linspace(1,10,20)
linspaced_20

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

5. Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.<br><br>
`import numpy as np`<br>
`a = np.arange(1, 26).reshape(5, -1)`<br>

In [58]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
# 20
a[3][-1]

20

In [61]:
a = np.array([[9, 10], [14, 15], [19, 20], [24, 25]])
a[2,-1]

20

In [72]:
a = np.array([ 6,  7,  8,  9, 10])
a[0]

6

In [64]:
a = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
a[1,-1]

20

In [74]:
a = np.array([[8, 9], [13, 14]])
a[1,:]

array([13, 14])

6. Calculate the sum of all the numbers in a.

In [76]:
np.sum(a)

44

7. Calculate the sum of each row in a.

In [79]:
np.sum(a, axis=1)

array([17, 27])

8. Extract all values of a greater than the mean of a (hint: use a boolean mask).

In [95]:
a[a > np.mean(a)]

array([13, 14])

9. Find the location of the minimum value in the following array b:<br><br>
`np.random.seed(123)`<br>
`b = np.random.randn(10)`<br>
`b`<br>

10. Find the location of the maximum value in the following 2D array c (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see post):<br><br>
`np.random.seed(123)`<br>
`c = np.random.randn(3, 2)`<br>
`c`<br>


# Pandas

1. In this set of practice exercises we’ll be investigating the carbon footprint of different foods. We’ll be leveraging a dataset compiled by Kasia Kulma and contributed to R’s Tidy Tuesday project.

Start by importing pandas with the alias pd.

In [96]:
import pandas as pd

2. Import the dataset as a dataframe named df from this url: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv

In [ ]:
df = pd.read_csv(f'')

3. How many rows and columns are there in the dataframe?

4. What is the type of data in each column of df?

5. What is the mean `co2_emission` of the whole dataset?

6. How many different kinds of foods are there in the dataset? How many countries are in the dataset?

7. What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

8. How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

9. Which country consumes the least amount of beef per person per year?

10. Which country consumes the most amount of soybeans per person per year?

11. What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

12. What is the total emissions of all other (non-meat) products in the dataset combined?